# BETTER DUELS by Francies


# Punizione
# Comando per chi abbandona il duello
punishment-command: "ban %player% 9d Uscito durante un duello"  # %player% player che ha sloggato


# Kit Manager
# possono essere inseriti altri kit, facendo attenzione alla configurazione di quelli di default
# di ogni kit puoi scegliere gli oggetti, la quantità dell'oggetto, il nome, la lore e gli incantamenti

kits:
  warrior:
    - material: NETHERITE_SWORD
      amount: 1
      name: "La spada spadosa"
      lore:
        - "Una spada molto spadosa"
      enchantments:
        SHARPNESS: 5
        SWEEPING_EDGE: 3
        FIRE_ASPECT: 2
        UNBREAKING: 3
    - material: NETHERITE_AXE
      amount: 1
      name: "Ascia Mesta"
      lore:
        - "Si dice sia l'ascia del boscaiolo di Clash Royale"
      enchantments:
        SHARPNESS: 5
        UNBREAKING: 3
    - material: NETHERITE_HELMET
      amount: 1
      name: "Corona di Spine"
      lore:
        - "Non serve precisare da dove viene..."
      enchantments:
        PROTECTION: 4
        THORNS: 3
        UNBREAKING: 3


# World Manager
world_duel: "duel" # mondo del duello
world_endDuel: "world" # mondo per ritornare dal duello

# posizione del respawn alla fine del duello
players_end_location:
  x: 0.0
  y: 100.0
  z: 0.0
# posizione nel mondo del duello
player1_location:  # imposta la posizione del primo giocatore
  x: 0.0
  y: 100.0
  z: 0.0
  yaw: 0.0    # se qui lo yaw è positivo, allora sotto sarà uguale ma negativo
  pitch: 0.0 # il pitch del primo e del secondo player sono uguali
player2_location: # imposta la posizione del secondo giocatore
  x: 10.0
  y: 100.0
  z: 10.0
  yaw: 0.0
  pitch: 0.0

# Messaggi
messages:
  prefix: "&7[&6BetterDuels&7] "
  win: "&aHai vinto il duello!"
  defeat: "&cSei stato sconfitto nel duello."
  no-perm: "&cNon hai il permesso per eseguire questo comando."
  no-perm-target: "&c%player% non ha il permesso di fare duelli." # %player% persona sfidata
  win-by-abbadon: "&aIl tuo avversario ha abbandonato il duello. Hai vinto!"
  duel-usage-command: "&eUtilizzo: /duel <nome_giocatore>"
  duel-accept-usage-command: "&eUtilizzo: /duelaccept <nome_giocatore>"
  duel-deny-usage-command: "&eUtilizzo: /dueldeny  <nome_giocatore>"
  no-duel-command-during-duel: "&cNon puoi iniziare un nuovo duello mentre sei già in uno."
  player-not-online: "&cIl giocatore specificato non è online."
  error-duel-youself: "&cNon puoi sfidarti da solo in un duello."
  already-in-a-duel: "&c%player% sta facendo un duello, aspetta che finisca!" # %player% player sfidato
  no-perm-kit: "&cNon hai il permesso di utilizzare questo kit."
  kit-received: "&aHai ricevuto il kit: %kit%." # %kit% nome del kit ricevuto
  inventory-restore: "&aEcco il tuo inventario!"
  inventory-restore-empty: "&cIl tuo inventario era vuoto"
  kit-only-during-duel: "&cPuoi scegliere un kit solo durante un duello!"
  kit-selected: "&aHai scelto il kit attendi...!" # %kit% nome del kit scelto
  kit-not-exist: "&cIl kit non esiste!"
  duel-request-sent: "&aHai inviato a %player% una sfida!" # %player% giocatore sfidato
  duel-request-received: "&aHai ricevuto una sfida da %player%" # %player% giocatore che ha chiesto il duello
  no-challenge: "&cNon sei stato sfidato!"
  duel-request-denied-target: "&cHai rifiutato il duello di %player%!" # %player% sfidante
  duel-request-accepted-target: "&aHai accettato il duello di %player%" # %player% sfidante
  duel-request-denied: "&cLa tua richiesta di duello a %player% è stata rifiutata." # %player% giocatore che ha rifiutato la richiesta
  duel-request-accepted: "&aLa tua richiesta di duello a %player% è stata accettata." # %player% giocatore che ha accettato la richiesta
  already-in-request: "&c%player% ha già un invito attivo!" # %player% giocatore sfidato
  duel-request-expired-target: "&cLa sfida che hai mandato a %player% è scaduta!" #%player% persona sfidata
  duel-request-expired: "&cLa sfida inviata da %player% è scaduta!" #%player% sfidante


GUI:
  name: "&cKITS"    # nome della GUI
  size: 9           # grandezza della gui, solo multipli di 9
  kitConfigs:       # per ogni kit che crei sopra, inserisci l'omonimo qui
    warrior:        # nome del kit
      material: "NETHERITE_SWORD" # icona della GUI rappresentante il kit, di default sarà un PAPER
      color: "&c"   # colore del nome del kit, usa &
    archer:
      material: "BOW"
      color: "&a"


#Gestione del countdown
countdown:
  title: "&a%count%"    #titolo del countdown, %count% tempo inserito sotto
  subtitle: "&ePreparati!"  #sottotitolo del countdown
  time-to-start: 5     #tempo del count down

# Configurazione del pulsante
duel:
  time-to-life: 60 #  tempo prima che scada una sfida

reward:
  amount: 1 #quantità
  material: DIAMOND # oggetto da ricevere
  command: "eco give %player% 200" # %player% giocatore che ha vinto