# BETTER DUELS by Francies


# Utils
punishment-command: "ban %player% 9d Uscito durante un combact"


# Kit Manager
kits:
  warrior:
    - material: NETHERITE_SWORD
      amount: 1
      name: "La spada spadosa"
      lore:
        - "Una spada molto spadosa"
      enchantments:
        SHARPNESS: 5
        SWEEPING_EDGE: 3
        FIRE_ASPECT: 2
        UNBREAKING: 3
    - material: NETHERITE_AXE
      amount: 1
      name: "Ascia Mesta"
      lore:
        - "Si dice sia l'ascia del boscaiolo di Clash Royale"
      enchantments:
        SHARPNESS: 5
        UNBREAKING: 3
    - material: NETHERITE_HELMET
      amount: 1
      name: "Corona di Spine"
      lore:
        - "Non serve precisare da dove viene..."
      enchantments:
        PROTECTION: 4
        THORNS: 3
        UNBREAKING: 3

# World Manager
world_duel: "world"
world_endDuel: "world"

players_end_location:
  x:
  y:
  z:

player1_location:
  x: 0.0
  y: 100.0
  z: 0.0

player2_location:
  x: 10.0
  y: 100.0
  z: 10.0


# Messages
messages:
  prefix: "&7[&6BetterDuels&7] "
  win: "&aHai vinto il duello!"
  defeat: "&cSei stato sconfitto nel duello."
  no-perm: "&cNon hai il permesso per eseguire questo comando."
  win-by-abbadon: "&aIl tuo avversario ha abbandonato il duello. Hai vinto!"
  duel-usage-command: "&eUtilizzo: /duel <nome_giocatore>"
  no-duel-command-during-duel: "&cNon puoi iniziare un nuovo duello mentre sei già in uno."
  player-not-online: "&cIl giocatore specificato non è online."
  error-duel-youself: "&cNon puoi sfidarti da solo in un duello."
  already-in-a-duel: "&cSei già impegnato in un duello."
  no-perm-kit: "&cNon hai il permesso di utilizzare questo kit."
  kit-received: "&aHai ricevuto il kit: %kit%."
